scrape_configs:
  - job_name: 'collector'
    scrape_interval: 1s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - collector:8888
          - collector:8889

  - job_name: 'cadvisor'
    scrape_interval: 1s
    static_configs:
      - targets: ['cadvisor:8080']
  
  - job_name: 'node_exporter'
    scrape_interval: 1s
    static_configs:
      - targets: ['node_exporter:9100']
