receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ":4317"
      http:
        endpoint: ":4318"
        include_metadata: true

processors:
  batch:

exporters:
  prometheus:
    endpoint: ":8889"
    namespace: "otel"
  logging:

extensions:
  health_check:
    endpoint: ":13133"
    response_body: {
      "healthy": "UP",
      "unhealthy": "DOWN"
    }

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: "debug"
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
